# Generated by Django 5.0 on 2023-12-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('I', 'Image'), ('P', 'PDF'), ('V', 'Video')], default=0, max_length=1)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('shared', models.BooleanField(default=False)),
                ('notes', models.ManyToManyField(to='main_app.note')),
                ('references', models.ManyToManyField(to='main_app.reference')),
            ],
        ),
    ]
