# Generated by Django 5.0 on 2024-01-03 19:02

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_collection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collection',
            name='notes',
            field=models.ManyToManyField(default='', to='main_app.note'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='references',
            field=models.ManyToManyField(default='', to='main_app.reference'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
