# Generated by Django 5.0 on 2024-01-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_profile_collections_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collections_saved',
        ),
        migrations.AddField(
            model_name='profile',
            name='collections_saved',
            field=models.ManyToManyField(null=True, to='main_app.collection'),
        ),
    ]
